# Nixpacks configuration for backend deployment
# Place this in backend/RealTimeTaskManager/.nixpacks/nixpacks.toml

[variables]
NIXPACKS_METADATA = "c#"

[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "./out/RealTimeTaskManager"