# Nixpacks configuration for backend-only deployment
# For use in Coolify with base directory: backend/RealTimeTaskManager

[variables]
NIXPACKS_METADATA = "c#"

[phases.setup]
nixPkgs = ["dotnet-sdk_8", "curl"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "./out/RealTimeTaskManager"

[variables.runtime]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:5000"