# This Docker Compose is for local development only
# For Coolify deployment, use the Dockerfile in backend/RealTimeTaskManager/

version: "3.8"

services:
  # ===========================
  # LOCAL DEVELOPMENT ONLY
  # ===========================
  # Use this for local development with: docker-compose up
  # For Coolify: Use Dockerfile deployment with separate MySQL service
  
  backend-local:
    build:
      context: ./backend/RealTimeTaskManager
      dockerfile: Dockerfile
    container_name: taskmanager-backend-local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=3306;Database=TaskManagerDB;Uid=root;Pwd=password;
    ports:
      - "5000:5000"
    profiles:
      - local-dev
