version: "3.8"

services:
  # ===========================
  # DATABASE  
  # ===========================
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-TaskManagerDB}
      MYSQL_USER: ${MYSQL_USER:-taskmanager}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
      interval: 30s

  # ===========================
  # BACKEND API ONLY
  # ===========================
  backend:
    build:
      context: ./backend/RealTimeTaskManager
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=${MYSQL_DATABASE:-TaskManagerDB};User=${MYSQL_USER:-taskmanager};Password=${MYSQL_PASSWORD};
      - Cors__AllowedOrigins=*
      - HealthChecks__Enabled=true
      - SwaggerUI__Enabled=${SWAGGER_ENABLED:-true}
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - backend_logs:/app/logs
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# ===========================
# VOLUMES
# ===========================
volumes:
  mysql_data:
  backend_logs: