version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: realtimetaskmanager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-SecureRootPassword123!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-RealTimeTaskManagerDB}
      MYSQL_USER: ${MYSQL_USER:-taskmanager}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-SecurePassword123!}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # .NET API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtimetaskmanager-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=${MYSQL_DATABASE:-RealTimeTaskManagerDB};Uid=${MYSQL_USER:-taskmanager};Pwd=${MYSQL_PASSWORD:-SecurePassword123!};SslMode=Preferred;
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-SecureRootPassword123!}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-RealTimeTaskManagerDB}
      - MYSQL_USER=${MYSQL_USER:-taskmanager}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-SecurePassword123!}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  taskmanager-network:
    driver: bridge
